baseURL = 'https://jnaranjo.dev/'
languageCode = 'en-us'
title = "Jose I. Naranjo - Software Developer based in Madrid"
theme = "ortree-theme"

defaultContentLanguage = 'en'
[languages]
  [languages.es]
    languageName = 'Español'
    title = 'Jose I. Naranjo - Programador en Madrid'
    weight = 10
    [languages.de.menu]
[[languages.es.menu.main]]
      name = 'Inicio'
      url = '/es/'
      weight = 1
[[languages.es.menu.main]]
      name = "Sobre mí"
      url = "/es/about/"
      weight = 2
[[languages.es.menu.main]]
      name = "Contacto"
      url = "/es/#contact"
      weight = 3
  [languages.en]
    languageName = 'English'
    weight = 0
    [languages.en.menu]
[[languages.en.menu.main]]
      name = 'Home'
      url = '/'
      weight = 1
[[languages.en.menu.main]]
      name = "About Me"
      url = "/about/"
      weight = 2
[[languages.en.menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 3

[[params.socialIcon]]
src = "/images/logos/linkedin.png"
alt = "LinkedIn"
url = "https://www.linkedin.com/in/joseignacionaranjo/"

[[params.socialIcon]]
src = "/images/logos/wellfound.png"
alt = "Wellfound"
url = "https://angel.co/u/jose-ignacio-naranjo-hernandez"
